Fuzz `execFile` and `spawn` on top of `exec` in CI

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -138,13 +138,13 @@ jobs:
         run: sudo apt-get -y install zsh
       - name: Install dependencies
         run: npm ci
-      - name: Fuzz
-        id: fuzz
+      - name: Fuzz exec/execSync
+        id: fuzz-exec
         shell: bash {0}
         env:
           FUZZ_SHELL: ${{ matrix.shell }}
         run: |
-          timeout 20m npm run fuzz exec
+          timeout 6m npm run fuzz exec
           export EXIT_CODE=$?
           if [[ ($EXIT_CODE == 124) ]]
           then
@@ -160,20 +160,94 @@ jobs:
             echo "::set-output name=exit-code::"$EXIT_CODE
           fi
       - name: Check for unexpected error
-        if: ${{ steps.fuzz.outputs.script-error == 'true' }}
+        if: ${{ steps.fuzz-exec.outputs.script-error == 'true' }}
         run: |
-          echo "Unexpected error: ${{ steps.fuzz.outputs.exit-code }}"
+          echo "Unexpected error: ${{ steps.fuzz-exec.outputs.exit-code }}"
           exit 1
       - name: Upload crash (if any)
-        if: ${{ steps.fuzz.outputs.fuzz-error == 'true' }}
+        if: ${{ steps.fuzz-exec.outputs.fuzz-error == 'true' }}
         uses: actions/upload-artifact@v3.1.0
         with:
-          name: fuzz-crash-${{ matrix.os }}-${{ matrix.shell }}
+          name: fuzz-crash-${{ matrix.os }}-${{ matrix.shell }}-exec
           path: |
             .corpus/
             crash-*
       - name: Error for fuzz crash
-        if: ${{ steps.fuzz.outputs.fuzz-error == 'true' }}
+        if: ${{ steps.fuzz-exec.outputs.fuzz-error == 'true' }}
+        run: exit 1
+      - name: Fuzz execFile/execFileSync
+        id: fuzz-execFile
+        shell: bash {0}
+        env:
+          FUZZ_SHELL: ${{ matrix.shell }}
+        run: |
+          timeout 6m npm run fuzz execFile
+          export EXIT_CODE=$?
+          if [[ ($EXIT_CODE == 124) ]]
+          then
+            echo "::set-output name=fuzz-error::false"
+            echo "::set-output name=script-error::false"
+          elif [[ ($EXIT_CODE == 1) ]]
+          then
+            echo "::set-output name=fuzz-error::true"
+            echo "::set-output name=script-error::false"
+          else
+            echo "::set-output name=fuzz-error::false"
+            echo "::set-output name=script-error::true"
+            echo "::set-output name=exit-code::"$EXIT_CODE
+          fi
+      - name: Check for unexpected error
+        if: ${{ steps.fuzz-execFile.outputs.script-error == 'true' }}
+        run: |
+          echo "Unexpected error: ${{ steps.fuzz-execFile.outputs.exit-code }}"
+          exit 1
+      - name: Upload crash (if any)
+        if: ${{ steps.fuzz-execFile.outputs.fuzz-error == 'true' }}
+        uses: actions/upload-artifact@v3.1.0
+        with:
+          name: fuzz-crash-${{ matrix.os }}-${{ matrix.shell }}-execFile
+          path: |
+            .corpus/
+            crash-*
+      - name: Error for fuzz crash
+        if: ${{ steps.fuzz-execFile.outputs.fuzz-error == 'true' }}
+        run: exit 1
+      - name: Fuzz spawn/spawnSync
+        id: fuzz-spawn
+        shell: bash {0}
+        env:
+          FUZZ_SHELL: ${{ matrix.shell }}
+        run: |
+          timeout 6m npm run fuzz spawn
+          export EXIT_CODE=$?
+          if [[ ($EXIT_CODE == 124) ]]
+          then
+            echo "::set-output name=fuzz-error::false"
+            echo "::set-output name=script-error::false"
+          elif [[ ($EXIT_CODE == 1) ]]
+          then
+            echo "::set-output name=fuzz-error::true"
+            echo "::set-output name=script-error::false"
+          else
+            echo "::set-output name=fuzz-error::false"
+            echo "::set-output name=script-error::true"
+            echo "::set-output name=exit-code::"$EXIT_CODE
+          fi
+      - name: Check for unexpected error
+        if: ${{ steps.fuzz-spawn.outputs.script-error == 'true' }}
+        run: |
+          echo "Unexpected error: ${{ steps.fuzz-spawn.outputs.exit-code }}"
+          exit 1
+      - name: Upload crash (if any)
+        if: ${{ steps.fuzz-spawn.outputs.fuzz-error == 'true' }}
+        uses: actions/upload-artifact@v3.1.0
+        with:
+          name: fuzz-crash-${{ matrix.os }}-${{ matrix.shell }}-spawn
+          path: |
+            .corpus/
+            crash-*
+      - name: Error for fuzz crash
+        if: ${{ steps.fuzz-spawn.outputs.fuzz-error == 'true' }}
         run: exit 1
   mutation:
     name: Mutation
