Add CI fuzzing of `execFile` and `fork`
Reduce the fuzz time per child_process function to 5 minutes each,
keeping the total of 20 minutes of fuzzing.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -177,13 +177,14 @@ jobs:
         run: sudo apt-get -y install zsh
       - name: Install dependencies
         run: npm ci
+
       - name: Fuzz exec/execSync
         id: fuzz-exec
         shell: bash {0}
         env:
           FUZZ_SHELL: ${{ matrix.shell }}
         run: |
-          timeout 10m npm run fuzz exec
+          timeout 5m npm run fuzz exec
           export EXIT_CODE=$?
           if [[ ($EXIT_CODE == 124) ]]
           then
@@ -214,13 +215,90 @@ jobs:
       - name: Error for fuzz crash
         if: ${{ steps.fuzz-exec.outputs.fuzz-error == 'true' }}
         run: exit 1
+
+      - name: Fuzz execFile/execFileSync
+        id: fuzz-exec-file
+        shell: bash {0}
+        env:
+          FUZZ_SHELL: ${{ matrix.shell }}
+        run: |
+          timeout 5m npm run fuzz execFile
+          export EXIT_CODE=$?
+          if [[ ($EXIT_CODE == 124) ]]
+          then
+            echo "::set-output name=fuzz-error::false"
+            echo "::set-output name=script-error::false"
+          elif [[ ($EXIT_CODE == 1) ]]
+          then
+            echo "::set-output name=fuzz-error::true"
+            echo "::set-output name=script-error::false"
+          else
+            echo "::set-output name=fuzz-error::false"
+            echo "::set-output name=script-error::true"
+            echo "::set-output name=exit-code::"$EXIT_CODE
+          fi
+      - name: Check for unexpected error
+        if: ${{ steps.fuzz-exec-file.outputs.script-error == 'true' }}
+        run: |
+          echo "Unexpected error: ${{ steps.fuzz-exec-file.outputs.exit-code }}"
+          exit 1
+      - name: Upload crash (if any)
+        if: ${{ steps.fuzz-exec-file.outputs.fuzz-error == 'true' }}
+        uses: actions/upload-artifact@v3.1.0
+        with:
+          name: fuzz-crash-${{ matrix.os }}-${{ matrix.name }}-exec-file
+          path: |
+            .corpus/
+            crash-*
+      - name: Error for fuzz crash
+        if: ${{ steps.fuzz-exec-file.outputs.fuzz-error == 'true' }}
+        run: exit 1
+
+      - name: Fuzz fork
+        id: fuzz-fork
+        shell: bash {0}
+        env:
+          FUZZ_SHELL: ${{ matrix.shell }}
+        run: |
+          timeout 5m npm run fuzz fork
+          export EXIT_CODE=$?
+          if [[ ($EXIT_CODE == 124) ]]
+          then
+            echo "::set-output name=fuzz-error::false"
+            echo "::set-output name=script-error::false"
+          elif [[ ($EXIT_CODE == 1) ]]
+          then
+            echo "::set-output name=fuzz-error::true"
+            echo "::set-output name=script-error::false"
+          else
+            echo "::set-output name=fuzz-error::false"
+            echo "::set-output name=script-error::true"
+            echo "::set-output name=exit-code::"$EXIT_CODE
+          fi
+      - name: Check for unexpected error
+        if: ${{ steps.fuzz-fork.outputs.script-error == 'true' }}
+        run: |
+          echo "Unexpected error: ${{ steps.fuzz-fork.outputs.exit-code }}"
+          exit 1
+      - name: Upload crash (if any)
+        if: ${{ steps.fuzz-fork.outputs.fuzz-error == 'true' }}
+        uses: actions/upload-artifact@v3.1.0
+        with:
+          name: fuzz-crash-${{ matrix.os }}-${{ matrix.name }}-fork
+          path: |
+            .corpus/
+            crash-*
+      - name: Error for fuzz crash
+        if: ${{ steps.fuzz-fork.outputs.fuzz-error == 'true' }}
+        run: exit 1
+
       - name: Fuzz spawn/spawnSync
         id: fuzz-spawn
         shell: bash {0}
         env:
           FUZZ_SHELL: ${{ matrix.shell }}
         run: |
-          timeout 10m npm run fuzz spawn
+          timeout 5m npm run fuzz spawn
           export EXIT_CODE=$?
           if [[ ($EXIT_CODE == 124) ]]
           then
